### ISSUE TITLE
[FEATURE] 비디오 플레이어 화면 구현

### ISSUE THREAD

**Issue by INAH-PAK** [hoyahozz/android-wanted-VideoRecorderApp#5]
## 🤔 목적

> 비디오 플레이어 화면 구현

## 📝 TO-DO

- [x] 녹화된 영상을 플레이 .
- [x] 화면 하단 컨트롤 바 - 재생 , 일시정지, 플레이 Seekbar
- [x]  Exo Player 라이브러리 구현
